#! /usr/bin/env bash
set -ex

BUILD_DATE=$(date -u '+%FT%TZ')

docker build . \
  --build-arg BUILD_DATE=$BUILD_DATE \
  --build-arg VERSION=$DOCKER_TAG \
  -f ${DOCKERFILE_PATH:-Dockerfile} \
  -t $IMAGE_NAME
